[package]
name = "tx_pool"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
libproto = { path = "../libproto" }
util = { path = "../util" }
cita-crypto = { path = "../cita-crypto" }
