[package]
name = "cita-sm2"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
rustc-serialize = "0.3"
serde = "1.0"
cita-types = { path = "../cita-types" }
util = { path = "../util" }
rlp = { path = "../rlp" }
libsm = { git = "https://github.com/cryptape/libsm", rev = "2c8295a576659ecef8ad18443646d236539cccf5" }

[features]
default = []
sha3hash = ["util/sha3hash"]
blake2bhash = ["util/blake2bhash"]
sm3hash = ["util/sm3hash"]
