ignore = [
    "rlp/src/common.rs",
    "rlp/src/compression.rs",
    "rlp/src/error.rs",
    "rlp/src/impls.rs",
    "rlp/src/lib.rs",
    "rlp/src/rlpin.rs",
    "rlp/src/stream.rs",
    "rlp/src/traits.rs",
    "rlp/src/untrusted_rlp.rs",

    "util/src/common.rs",
    "util/src/nibblevec.rs",
    "util/src/bytes.rs",
    "util/src/error.rs",
    "util/src/cache.rs",
    "util/src/nibbleslice.rs",

    "db/src/journaldb/mod.rs",
    "db/src/journaldb/overlayrecentdb.rs",
    "db/src/journaldb/earlymergedb.rs",
    "db/src/journaldb/traits.rs",
    "db/src/journaldb/archivedb.rs",
    "db/src/journaldb/refcounteddb.rs",
    "db/src/trie/sectriedb.rs",
    "db/src/trie/fatdbmut.rs",
    "db/src/trie/lookup.rs",
    "db/src/trie/triedb.rs",
    "db/src/trie/mod.rs",
    "db/src/trie/standardmap.rs",
    "db/src/trie/node.rs",
    "db/src/trie/fatdb.rs",
    "db/src/trie/triedbmut.rs",
    "db/src/trie/sectriedbmut.rs",
    "db/src/hashdb.rs",
    "db/src/overlaydb.rs",
    "db/src/memorydb.rs",
    "db/src/kvdb/mod.rs",
    "db/src/kvdb/in_memory.rs",
    "db/src/kvdb/rocksdb.rs",
]
