[package]
name = "engine"
version = "0.6.0"
authors = ["Cryptape Technologies <arch@cryptape.com>"]

[dependencies]
libproto = { path = "../libproto" }
util = { path = "../util" }
protobuf = { version = "^1.0.0" }
cita-crypto = { path = "../cita-crypto" }
engine_json = { path = "../engine_json" }
proof = { path = "../proof" }
pubsub = { path = "../pubsub" }
