defaults: &defaults
  docker:
    - image: cita/cita-build:ubuntu-18.04-20180523
  working_directory: ~/cita-build

version: 2
jobs:
  format:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: format
          command: 'cargo fmt --all  -- --check'
  build:
    <<: *defaults
    steps:
      - checkout
      - run: 'cargo generate-lockfile'
      - restore_cache:
          key: build-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: build
          command: '.ci-scripts/loop_crates_to_run build'
      - save_cache:
          key: build-cache-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
  test:
    <<: *defaults
    steps:
      - checkout
      - run: 'cargo generate-lockfile'
      - restore_cache:
          key: test-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: test
          command: '.ci-scripts/loop_crates_to_run test'
      - save_cache:
          key: test-cache-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2

  btd:
    jobs:
      - format
      - build:
          requires:
            - format
      - test:
          requires:
            - format
